// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi




// SensorEvent - Событие датчика
type SensorEvent struct {

	// Серийный номер датчика
	SensorSerialNumber string `json:"sensor_serial_number"`

	// Информация от датчика
	Payload int64 `json:"payload"`
}

// AssertSensorEventRequired checks if the required fields are not zero-ed
func AssertSensorEventRequired(obj SensorEvent) error {
	elements := map[string]interface{}{
		"sensor_serial_number": obj.SensorSerialNumber,
		"payload": obj.Payload,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSensorEventConstraints checks if the values respects the defined constraints
func AssertSensorEventConstraints(obj SensorEvent) error {
	return nil
}
