package learning

// Code generated by http://github.com/gojuno/minimock (dev). DO NOT EDIT.

//go:generate minimock -i hw4/internal/learning.Repo -o ./repo_mock_test.go -n RepoMock

import (
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/gojuno/minimock/v3"
)

// RepoMock implements Repo
type RepoMock struct {
	t minimock.Tester

	funcGetAllSubjects          func() (sa1 []string, b1 bool)
	inspectFuncGetAllSubjects   func()
	afterGetAllSubjectsCounter  uint64
	beforeGetAllSubjectsCounter uint64
	GetAllSubjectsMock          mRepoMockGetAllSubjects

	funcGetAllSubjectsInfo          func() (sa1 []subjectInfo, b1 bool)
	inspectFuncGetAllSubjectsInfo   func()
	afterGetAllSubjectsInfoCounter  uint64
	beforeGetAllSubjectsInfoCounter uint64
	GetAllSubjectsInfoMock          mRepoMockGetAllSubjectsInfo

	funcGetStudentInfo          func(id int64) (sp1 *studentInfo, b1 bool)
	inspectFuncGetStudentInfo   func(id int64)
	afterGetStudentInfoCounter  uint64
	beforeGetStudentInfoCounter uint64
	GetStudentInfoMock          mRepoMockGetStudentInfo
}

// NewRepoMock returns a mock for Repo
func NewRepoMock(t minimock.Tester) *RepoMock {
	m := &RepoMock{t: t}
	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.GetAllSubjectsMock = mRepoMockGetAllSubjects{mock: m}

	m.GetAllSubjectsInfoMock = mRepoMockGetAllSubjectsInfo{mock: m}

	m.GetStudentInfoMock = mRepoMockGetStudentInfo{mock: m}
	m.GetStudentInfoMock.callArgs = []*RepoMockGetStudentInfoParams{}

	return m
}

type mRepoMockGetAllSubjects struct {
	mock               *RepoMock
	defaultExpectation *RepoMockGetAllSubjectsExpectation
	expectations       []*RepoMockGetAllSubjectsExpectation
}

// RepoMockGetAllSubjectsExpectation specifies expectation struct of the Repo.GetAllSubjects
type RepoMockGetAllSubjectsExpectation struct {
	mock *RepoMock

	results *RepoMockGetAllSubjectsResults
	Counter uint64
}

// RepoMockGetAllSubjectsResults contains results of the Repo.GetAllSubjects
type RepoMockGetAllSubjectsResults struct {
	sa1 []string
	b1  bool
}

// Expect sets up expected params for Repo.GetAllSubjects
func (mmGetAllSubjects *mRepoMockGetAllSubjects) Expect() *mRepoMockGetAllSubjects {
	if mmGetAllSubjects.mock.funcGetAllSubjects != nil {
		mmGetAllSubjects.mock.t.Fatalf("RepoMock.GetAllSubjects mock is already set by Set")
	}

	if mmGetAllSubjects.defaultExpectation == nil {
		mmGetAllSubjects.defaultExpectation = &RepoMockGetAllSubjectsExpectation{}
	}

	return mmGetAllSubjects
}

// Inspect accepts an inspector function that has same arguments as the Repo.GetAllSubjects
func (mmGetAllSubjects *mRepoMockGetAllSubjects) Inspect(f func()) *mRepoMockGetAllSubjects {
	if mmGetAllSubjects.mock.inspectFuncGetAllSubjects != nil {
		mmGetAllSubjects.mock.t.Fatalf("Inspect function is already set for RepoMock.GetAllSubjects")
	}

	mmGetAllSubjects.mock.inspectFuncGetAllSubjects = f

	return mmGetAllSubjects
}

// Return sets up results that will be returned by Repo.GetAllSubjects
func (mmGetAllSubjects *mRepoMockGetAllSubjects) Return(sa1 []string, b1 bool) *RepoMock {
	if mmGetAllSubjects.mock.funcGetAllSubjects != nil {
		mmGetAllSubjects.mock.t.Fatalf("RepoMock.GetAllSubjects mock is already set by Set")
	}

	if mmGetAllSubjects.defaultExpectation == nil {
		mmGetAllSubjects.defaultExpectation = &RepoMockGetAllSubjectsExpectation{mock: mmGetAllSubjects.mock}
	}
	mmGetAllSubjects.defaultExpectation.results = &RepoMockGetAllSubjectsResults{sa1, b1}
	return mmGetAllSubjects.mock
}

// Set uses given function f to mock the Repo.GetAllSubjects method
func (mmGetAllSubjects *mRepoMockGetAllSubjects) Set(f func() (sa1 []string, b1 bool)) *RepoMock {
	if mmGetAllSubjects.defaultExpectation != nil {
		mmGetAllSubjects.mock.t.Fatalf("Default expectation is already set for the Repo.GetAllSubjects method")
	}

	if len(mmGetAllSubjects.expectations) > 0 {
		mmGetAllSubjects.mock.t.Fatalf("Some expectations are already set for the Repo.GetAllSubjects method")
	}

	mmGetAllSubjects.mock.funcGetAllSubjects = f
	return mmGetAllSubjects.mock
}

// GetAllSubjects implements Repo
func (mmGetAllSubjects *RepoMock) GetAllSubjects() (sa1 []string, b1 bool) {
	mm_atomic.AddUint64(&mmGetAllSubjects.beforeGetAllSubjectsCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAllSubjects.afterGetAllSubjectsCounter, 1)

	if mmGetAllSubjects.inspectFuncGetAllSubjects != nil {
		mmGetAllSubjects.inspectFuncGetAllSubjects()
	}

	if mmGetAllSubjects.GetAllSubjectsMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAllSubjects.GetAllSubjectsMock.defaultExpectation.Counter, 1)

		mm_results := mmGetAllSubjects.GetAllSubjectsMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAllSubjects.t.Fatal("No results are set for the RepoMock.GetAllSubjects")
		}
		return (*mm_results).sa1, (*mm_results).b1
	}
	if mmGetAllSubjects.funcGetAllSubjects != nil {
		return mmGetAllSubjects.funcGetAllSubjects()
	}
	mmGetAllSubjects.t.Fatalf("Unexpected call to RepoMock.GetAllSubjects.")
	return
}

// GetAllSubjectsAfterCounter returns a count of finished RepoMock.GetAllSubjects invocations
func (mmGetAllSubjects *RepoMock) GetAllSubjectsAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjects.afterGetAllSubjectsCounter)
}

// GetAllSubjectsBeforeCounter returns a count of RepoMock.GetAllSubjects invocations
func (mmGetAllSubjects *RepoMock) GetAllSubjectsBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjects.beforeGetAllSubjectsCounter)
}

// MinimockGetAllSubjectsDone returns true if the count of the GetAllSubjects invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockGetAllSubjectsDone() bool {
	for _, e := range m.GetAllSubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjects != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetAllSubjectsInspect logs each unmet expectation
func (m *RepoMock) MinimockGetAllSubjectsInspect() {
	for _, e := range m.GetAllSubjectsMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to RepoMock.GetAllSubjects")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		m.t.Error("Expected call to RepoMock.GetAllSubjects")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjects != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsCounter) < 1 {
		m.t.Error("Expected call to RepoMock.GetAllSubjects")
	}
}

type mRepoMockGetAllSubjectsInfo struct {
	mock               *RepoMock
	defaultExpectation *RepoMockGetAllSubjectsInfoExpectation
	expectations       []*RepoMockGetAllSubjectsInfoExpectation
}

// RepoMockGetAllSubjectsInfoExpectation specifies expectation struct of the Repo.GetAllSubjectsInfo
type RepoMockGetAllSubjectsInfoExpectation struct {
	mock *RepoMock

	results *RepoMockGetAllSubjectsInfoResults
	Counter uint64
}

// RepoMockGetAllSubjectsInfoResults contains results of the Repo.GetAllSubjectsInfo
type RepoMockGetAllSubjectsInfoResults struct {
	sa1 []subjectInfo
	b1  bool
}

// Expect sets up expected params for Repo.GetAllSubjectsInfo
func (mmGetAllSubjectsInfo *mRepoMockGetAllSubjectsInfo) Expect() *mRepoMockGetAllSubjectsInfo {
	if mmGetAllSubjectsInfo.mock.funcGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("RepoMock.GetAllSubjectsInfo mock is already set by Set")
	}

	if mmGetAllSubjectsInfo.defaultExpectation == nil {
		mmGetAllSubjectsInfo.defaultExpectation = &RepoMockGetAllSubjectsInfoExpectation{}
	}

	return mmGetAllSubjectsInfo
}

// Inspect accepts an inspector function that has same arguments as the Repo.GetAllSubjectsInfo
func (mmGetAllSubjectsInfo *mRepoMockGetAllSubjectsInfo) Inspect(f func()) *mRepoMockGetAllSubjectsInfo {
	if mmGetAllSubjectsInfo.mock.inspectFuncGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("Inspect function is already set for RepoMock.GetAllSubjectsInfo")
	}

	mmGetAllSubjectsInfo.mock.inspectFuncGetAllSubjectsInfo = f

	return mmGetAllSubjectsInfo
}

// Return sets up results that will be returned by Repo.GetAllSubjectsInfo
func (mmGetAllSubjectsInfo *mRepoMockGetAllSubjectsInfo) Return(sa1 []subjectInfo, b1 bool) *RepoMock {
	if mmGetAllSubjectsInfo.mock.funcGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("RepoMock.GetAllSubjectsInfo mock is already set by Set")
	}

	if mmGetAllSubjectsInfo.defaultExpectation == nil {
		mmGetAllSubjectsInfo.defaultExpectation = &RepoMockGetAllSubjectsInfoExpectation{mock: mmGetAllSubjectsInfo.mock}
	}
	mmGetAllSubjectsInfo.defaultExpectation.results = &RepoMockGetAllSubjectsInfoResults{sa1, b1}
	return mmGetAllSubjectsInfo.mock
}

// Set uses given function f to mock the Repo.GetAllSubjectsInfo method
func (mmGetAllSubjectsInfo *mRepoMockGetAllSubjectsInfo) Set(f func() (sa1 []subjectInfo, b1 bool)) *RepoMock {
	if mmGetAllSubjectsInfo.defaultExpectation != nil {
		mmGetAllSubjectsInfo.mock.t.Fatalf("Default expectation is already set for the Repo.GetAllSubjectsInfo method")
	}

	if len(mmGetAllSubjectsInfo.expectations) > 0 {
		mmGetAllSubjectsInfo.mock.t.Fatalf("Some expectations are already set for the Repo.GetAllSubjectsInfo method")
	}

	mmGetAllSubjectsInfo.mock.funcGetAllSubjectsInfo = f
	return mmGetAllSubjectsInfo.mock
}

// GetAllSubjectsInfo implements Repo
func (mmGetAllSubjectsInfo *RepoMock) GetAllSubjectsInfo() (sa1 []subjectInfo, b1 bool) {
	mm_atomic.AddUint64(&mmGetAllSubjectsInfo.beforeGetAllSubjectsInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmGetAllSubjectsInfo.afterGetAllSubjectsInfoCounter, 1)

	if mmGetAllSubjectsInfo.inspectFuncGetAllSubjectsInfo != nil {
		mmGetAllSubjectsInfo.inspectFuncGetAllSubjectsInfo()
	}

	if mmGetAllSubjectsInfo.GetAllSubjectsInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetAllSubjectsInfo.GetAllSubjectsInfoMock.defaultExpectation.Counter, 1)

		mm_results := mmGetAllSubjectsInfo.GetAllSubjectsInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmGetAllSubjectsInfo.t.Fatal("No results are set for the RepoMock.GetAllSubjectsInfo")
		}
		return (*mm_results).sa1, (*mm_results).b1
	}
	if mmGetAllSubjectsInfo.funcGetAllSubjectsInfo != nil {
		return mmGetAllSubjectsInfo.funcGetAllSubjectsInfo()
	}
	mmGetAllSubjectsInfo.t.Fatalf("Unexpected call to RepoMock.GetAllSubjectsInfo.")
	return
}

// GetAllSubjectsInfoAfterCounter returns a count of finished RepoMock.GetAllSubjectsInfo invocations
func (mmGetAllSubjectsInfo *RepoMock) GetAllSubjectsInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjectsInfo.afterGetAllSubjectsInfoCounter)
}

// GetAllSubjectsInfoBeforeCounter returns a count of RepoMock.GetAllSubjectsInfo invocations
func (mmGetAllSubjectsInfo *RepoMock) GetAllSubjectsInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetAllSubjectsInfo.beforeGetAllSubjectsInfoCounter)
}

// MinimockGetAllSubjectsInfoDone returns true if the count of the GetAllSubjectsInfo invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockGetAllSubjectsInfoDone() bool {
	for _, e := range m.GetAllSubjectsInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjectsInfo != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetAllSubjectsInfoInspect logs each unmet expectation
func (m *RepoMock) MinimockGetAllSubjectsInfoInspect() {
	for _, e := range m.GetAllSubjectsInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Error("Expected call to RepoMock.GetAllSubjectsInfo")
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetAllSubjectsInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		m.t.Error("Expected call to RepoMock.GetAllSubjectsInfo")
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetAllSubjectsInfo != nil && mm_atomic.LoadUint64(&m.afterGetAllSubjectsInfoCounter) < 1 {
		m.t.Error("Expected call to RepoMock.GetAllSubjectsInfo")
	}
}

type mRepoMockGetStudentInfo struct {
	mock               *RepoMock
	defaultExpectation *RepoMockGetStudentInfoExpectation
	expectations       []*RepoMockGetStudentInfoExpectation

	callArgs []*RepoMockGetStudentInfoParams
	mutex    sync.RWMutex
}

// RepoMockGetStudentInfoExpectation specifies expectation struct of the Repo.GetStudentInfo
type RepoMockGetStudentInfoExpectation struct {
	mock    *RepoMock
	params  *RepoMockGetStudentInfoParams
	results *RepoMockGetStudentInfoResults
	Counter uint64
}

// RepoMockGetStudentInfoParams contains parameters of the Repo.GetStudentInfo
type RepoMockGetStudentInfoParams struct {
	id int64
}

// RepoMockGetStudentInfoResults contains results of the Repo.GetStudentInfo
type RepoMockGetStudentInfoResults struct {
	sp1 *studentInfo
	b1  bool
}

// Expect sets up expected params for Repo.GetStudentInfo
func (mmGetStudentInfo *mRepoMockGetStudentInfo) Expect(id int64) *mRepoMockGetStudentInfo {
	if mmGetStudentInfo.mock.funcGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("RepoMock.GetStudentInfo mock is already set by Set")
	}

	if mmGetStudentInfo.defaultExpectation == nil {
		mmGetStudentInfo.defaultExpectation = &RepoMockGetStudentInfoExpectation{}
	}

	mmGetStudentInfo.defaultExpectation.params = &RepoMockGetStudentInfoParams{id}
	for _, e := range mmGetStudentInfo.expectations {
		if minimock.Equal(e.params, mmGetStudentInfo.defaultExpectation.params) {
			mmGetStudentInfo.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetStudentInfo.defaultExpectation.params)
		}
	}

	return mmGetStudentInfo
}

// Inspect accepts an inspector function that has same arguments as the Repo.GetStudentInfo
func (mmGetStudentInfo *mRepoMockGetStudentInfo) Inspect(f func(id int64)) *mRepoMockGetStudentInfo {
	if mmGetStudentInfo.mock.inspectFuncGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("Inspect function is already set for RepoMock.GetStudentInfo")
	}

	mmGetStudentInfo.mock.inspectFuncGetStudentInfo = f

	return mmGetStudentInfo
}

// Return sets up results that will be returned by Repo.GetStudentInfo
func (mmGetStudentInfo *mRepoMockGetStudentInfo) Return(sp1 *studentInfo, b1 bool) *RepoMock {
	if mmGetStudentInfo.mock.funcGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("RepoMock.GetStudentInfo mock is already set by Set")
	}

	if mmGetStudentInfo.defaultExpectation == nil {
		mmGetStudentInfo.defaultExpectation = &RepoMockGetStudentInfoExpectation{mock: mmGetStudentInfo.mock}
	}
	mmGetStudentInfo.defaultExpectation.results = &RepoMockGetStudentInfoResults{sp1, b1}
	return mmGetStudentInfo.mock
}

// Set uses given function f to mock the Repo.GetStudentInfo method
func (mmGetStudentInfo *mRepoMockGetStudentInfo) Set(f func(id int64) (sp1 *studentInfo, b1 bool)) *RepoMock {
	if mmGetStudentInfo.defaultExpectation != nil {
		mmGetStudentInfo.mock.t.Fatalf("Default expectation is already set for the Repo.GetStudentInfo method")
	}

	if len(mmGetStudentInfo.expectations) > 0 {
		mmGetStudentInfo.mock.t.Fatalf("Some expectations are already set for the Repo.GetStudentInfo method")
	}

	mmGetStudentInfo.mock.funcGetStudentInfo = f
	return mmGetStudentInfo.mock
}

// When sets expectation for the Repo.GetStudentInfo which will trigger the result defined by the following
// Then helper
func (mmGetStudentInfo *mRepoMockGetStudentInfo) When(id int64) *RepoMockGetStudentInfoExpectation {
	if mmGetStudentInfo.mock.funcGetStudentInfo != nil {
		mmGetStudentInfo.mock.t.Fatalf("RepoMock.GetStudentInfo mock is already set by Set")
	}

	expectation := &RepoMockGetStudentInfoExpectation{
		mock:   mmGetStudentInfo.mock,
		params: &RepoMockGetStudentInfoParams{id},
	}
	mmGetStudentInfo.expectations = append(mmGetStudentInfo.expectations, expectation)
	return expectation
}

// Then sets up Repo.GetStudentInfo return parameters for the expectation previously defined by the When method
func (e *RepoMockGetStudentInfoExpectation) Then(sp1 *studentInfo, b1 bool) *RepoMock {
	e.results = &RepoMockGetStudentInfoResults{sp1, b1}
	return e.mock
}

// GetStudentInfo implements Repo
func (mmGetStudentInfo *RepoMock) GetStudentInfo(id int64) (sp1 *studentInfo, b1 bool) {
	mm_atomic.AddUint64(&mmGetStudentInfo.beforeGetStudentInfoCounter, 1)
	defer mm_atomic.AddUint64(&mmGetStudentInfo.afterGetStudentInfoCounter, 1)

	if mmGetStudentInfo.inspectFuncGetStudentInfo != nil {
		mmGetStudentInfo.inspectFuncGetStudentInfo(id)
	}

	mm_params := &RepoMockGetStudentInfoParams{id}

	// Record call args
	mmGetStudentInfo.GetStudentInfoMock.mutex.Lock()
	mmGetStudentInfo.GetStudentInfoMock.callArgs = append(mmGetStudentInfo.GetStudentInfoMock.callArgs, mm_params)
	mmGetStudentInfo.GetStudentInfoMock.mutex.Unlock()

	for _, e := range mmGetStudentInfo.GetStudentInfoMock.expectations {
		if minimock.Equal(e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.sp1, e.results.b1
		}
	}

	if mmGetStudentInfo.GetStudentInfoMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetStudentInfo.GetStudentInfoMock.defaultExpectation.Counter, 1)
		mm_want := mmGetStudentInfo.GetStudentInfoMock.defaultExpectation.params
		mm_got := RepoMockGetStudentInfoParams{id}
		if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetStudentInfo.t.Errorf("RepoMock.GetStudentInfo got unexpected parameters, want: %#v, got: %#v%s\n", *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetStudentInfo.GetStudentInfoMock.defaultExpectation.results
		if mm_results == nil {
			mmGetStudentInfo.t.Fatal("No results are set for the RepoMock.GetStudentInfo")
		}
		return (*mm_results).sp1, (*mm_results).b1
	}
	if mmGetStudentInfo.funcGetStudentInfo != nil {
		return mmGetStudentInfo.funcGetStudentInfo(id)
	}
	mmGetStudentInfo.t.Fatalf("Unexpected call to RepoMock.GetStudentInfo. %v", id)
	return
}

// GetStudentInfoAfterCounter returns a count of finished RepoMock.GetStudentInfo invocations
func (mmGetStudentInfo *RepoMock) GetStudentInfoAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStudentInfo.afterGetStudentInfoCounter)
}

// GetStudentInfoBeforeCounter returns a count of RepoMock.GetStudentInfo invocations
func (mmGetStudentInfo *RepoMock) GetStudentInfoBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetStudentInfo.beforeGetStudentInfoCounter)
}

// Calls returns a list of arguments used in each call to RepoMock.GetStudentInfo.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetStudentInfo *mRepoMockGetStudentInfo) Calls() []*RepoMockGetStudentInfoParams {
	mmGetStudentInfo.mutex.RLock()

	argCopy := make([]*RepoMockGetStudentInfoParams, len(mmGetStudentInfo.callArgs))
	copy(argCopy, mmGetStudentInfo.callArgs)

	mmGetStudentInfo.mutex.RUnlock()

	return argCopy
}

// MinimockGetStudentInfoDone returns true if the count of the GetStudentInfo invocations corresponds
// the number of defined expectations
func (m *RepoMock) MinimockGetStudentInfoDone() bool {
	for _, e := range m.GetStudentInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetStudentInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		return false
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStudentInfo != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		return false
	}
	return true
}

// MinimockGetStudentInfoInspect logs each unmet expectation
func (m *RepoMock) MinimockGetStudentInfoInspect() {
	for _, e := range m.GetStudentInfoMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to RepoMock.GetStudentInfo with params: %#v", *e.params)
		}
	}

	// if default expectation was set then invocations count should be greater than zero
	if m.GetStudentInfoMock.defaultExpectation != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		if m.GetStudentInfoMock.defaultExpectation.params == nil {
			m.t.Error("Expected call to RepoMock.GetStudentInfo")
		} else {
			m.t.Errorf("Expected call to RepoMock.GetStudentInfo with params: %#v", *m.GetStudentInfoMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetStudentInfo != nil && mm_atomic.LoadUint64(&m.afterGetStudentInfoCounter) < 1 {
		m.t.Error("Expected call to RepoMock.GetStudentInfo")
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *RepoMock) MinimockFinish() {
	if !m.minimockDone() {
		m.MinimockGetAllSubjectsInspect()

		m.MinimockGetAllSubjectsInfoInspect()

		m.MinimockGetStudentInfoInspect()
		m.t.FailNow()
	}
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *RepoMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *RepoMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockGetAllSubjectsDone() &&
		m.MinimockGetAllSubjectsInfoDone() &&
		m.MinimockGetStudentInfoDone()
}
