// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi

import (
	"errors"
)

// SensorToUserBinding - Связка датчика с пользователем
type SensorToUserBinding struct {

	// Идентификатор датчика
	SensorId int64 `json:"sensor_id"`
}

// AssertSensorToUserBindingRequired checks if the required fields are not zero-ed
func AssertSensorToUserBindingRequired(obj SensorToUserBinding) error {
	elements := map[string]interface{}{
		"sensor_id": obj.SensorId,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSensorToUserBindingConstraints checks if the values respects the defined constraints
func AssertSensorToUserBindingConstraints(obj SensorToUserBinding) error {
	if obj.SensorId < 1 {
		return &ParsingError{Err: errors.New(errMsgMinValueConstraint)}
	}
	return nil
}
