// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi

// SensorToCreate - Датчик умного дома, который надо создать
type SensorToCreate struct {

	// Серийный номер
	SerialNumber string `json:"serial_number"`

	// Тип
	Type string `json:"type"`

	// Описание
	Description string `json:"description"`

	// Флаг активности датчика
	IsActive bool `json:"is_active"`
}

// AssertSensorToCreateRequired checks if the required fields are not zero-ed
func AssertSensorToCreateRequired(obj SensorToCreate) error {
	elements := map[string]interface{}{
		"serial_number": obj.SerialNumber,
		"type":          obj.Type,
		"description":   obj.Description,
		"is_active":     obj.IsActive,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertSensorToCreateConstraints checks if the values respects the defined constraints
func AssertSensorToCreateConstraints(obj SensorToCreate) error {
	return nil
}
