// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi

// UserToCreate - Пользователь умного дома, которого надо создать
type UserToCreate struct {

	// Имя
	Name string `json:"name"`
}

// AssertUserToCreateRequired checks if the required fields are not zero-ed
func AssertUserToCreateRequired(obj UserToCreate) error {
	elements := map[string]interface{}{
		"name": obj.Name,
	}
	for name, el := range elements {
		if isZero := IsZeroValue(el); isZero {
			return &RequiredError{Field: name}
		}
	}

	return nil
}

// AssertUserToCreateConstraints checks if the values respects the defined constraints
func AssertUserToCreateConstraints(obj UserToCreate) error {
	return nil
}
