// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi

// User - Пользователь умного дома
type User struct {

	// Идентификатор
	Id int64 `json:"id"`

	// Имя
	Name string `json:"name"`
}
