// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi

// Error - Ошибка исполнения запроса
type Error struct {

	// Причина
	Reason string `json:"reason"`
}
