// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi

import (
	"time"
)

type GetSensorHistory200ResponseInner struct {

	// Дата и время события
	Timestamp time.Time `json:"timestamp,omitempty"`

	// Значение датчика
	Payload int64 `json:"payload,omitempty"`
}
