// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

/*
 * API умного дома
 *
 * Интерфейс управления и мониторинга устройствами умного дома
 *
 * API version: 0.1
 */

package openapi

import (
	"time"
)

// Sensor - Датчик умного дома
type Sensor struct {

	// Идентификатор
	Id int64 `json:"id"`

	// Серийный номер
	SerialNumber string `json:"serial_number"`

	// Тип
	Type string `json:"type"`

	// Состояние датчика, соответствует значению в payload последнего обработанного события.
	CurrentState int64 `json:"current_state"`

	// Описание
	Description string `json:"description"`

	// Флаг активности датчика
	IsActive bool `json:"is_active"`

	// Дата/время регистрации
	RegisteredAt time.Time `json:"registered_at"`

	// Время последнего события
	LastActivity time.Time `json:"last_activity"`
}
